### ISSUE TITLE
help: having trouble getting the bot to see messages

### ISSUE THREAD

**Issue by Place1** [blazeu/hubot-facebook#4]
Hey! Love the project and wanted to have a fiddle with it. i've set up my bot to just catchAll messages and log them to a file.

When i run the bot with the facebook adapter (instead of just the shell) it's not catching any messages.
This is the output when it starts.

```
info Logging in...
info Logged in
info Request to reconnect
info Request to pull 1
info Request to pull 2
info Request to thread_sync
info Done logging in.
```

Am i correct in thinking that once the bot has logged in using the username/password I set it should be able to catchAll all the messages i recieve from others on facebook both individually and in group chats?

Would be great to get some feedback to help my understanding :D

Update:
So i did a quick test using 'facebook-chat-api' which you use internally, and i got it working with myself by using `api.setOptions({selfListen: true})` it'd be good to learn how to set that when using hubot

**Comment by blazeu** [comment]
The npm version is buggy,
use the master branch or the get-user-name branch

If its still not receiving messages, maybe its because of Schmavery/facebook-chat-api#273

Really sorry for the inconvenience, I haven't had time to update this.

**Comment by Place1** [comment]
ok i'll take another look tomorrow evening! thanks for the fast response. No worries :)
